# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

NCutY3V1 <- function(Cys, Wys, Wxs) {
    .Call('NCutYX_NCutY3V1', PACKAGE = 'NCutYX', Cys, Wys, Wxs)
}

NCutLayer3V1 <- function(Cys, Wzs, Wys, Wxs, Wzyxs) {
    .Call('NCutYX_NCutLayer3V1', PACKAGE = 'NCutYX', Cys, Wzs, Wys, Wxs, Wzyxs)
}

